Stable Marriage problem and solution
TheAlgorithms/C-Sharp pull request #173
Opened 2020-10-10 17:38 UTC by brogowski

Hello,

I've implemented solution to Stable Marriage problem based on Gale–Shapley algorithm mentioned in #111.

- [ ] I have performed a self-review of my code
- [ ] My code follows the style guidelines of this project
- [ ] I have added comments to hard-to-understand areas of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have made corresponding changes to the comments
- [ ] I have made corresponding changes to the README.md

2020-10-10 17:40 UTC, siriak commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- Algorithms/Problems/StableMarriage/GaleShapley.cs  8
- Algorithms/Problems/StableMarriage/Accepter.cs  2
- Algorithms.Tests/Problems/StableMarriage/GaleShapleyTests.cs  2
- Algorithms/Problems/StableMarriage/Proposer.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6318000&bid=20538743)

2020-10-10 17:40 UTC, siriak commented on Algorithms/Problems/StableMarriage/GaleShapley.cs
> +                        if (accepter.PrefersOverCurrent(newProposer))
Codacy found an issue: [Refactor this code to not nest more than 3 control flow statements.](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6318000)

2020-10-10 18:16 UTC, siriak commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms.Tests/Problems/StableMarriage/GaleShapleyTests.cs  3
- Algorithms/Problems/StableMarriage/Proposer.cs  1
- Algorithms/Problems/StableMarriage/GaleShapley.cs  5
- Algorithms/Problems/StableMarriage/Accepter.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6318000&bid=20538743)

2020-10-11 16:15 UTC, siriak requested changes
Overall looks good, I've left a couple of comments on implementation details that are important and make the algorithm run in O(n^3) instead of advertised O(n^2).

2020-10-11 16:15 UTC, siriak commented on Algorithms/Problems/StableMarriage/GaleShapley.cs
> +            var matchingSession = proposers.Select(p => (Proposer: p, Accepters: accepters.OrderBy(a => p.Score(a)).ToList())).ToArray();
There is this list already in   `public List<Accepter> PreferenceOrder { get; set; } = new List<Accepter>();`.
So just need to pass p.

2020-10-11 16:15 UTC, siriak commented on Algorithms/Problems/StableMarriage/GaleShapley.cs
> +                session.Accepters.Remove(accepter);
Accepters is a list, which means that his operation takes O(n) time, which brings total algorithm time to O(n^3), which is not correct. Use LinkedList<Accepter> here.

2020-10-11 16:15 UTC, siriak commented on Algorithms/Problems/StableMarriage/GaleShapley.cs
> +
No need for this as they should be null before calling the algorithm

2020-10-11 17:27 UTC, siriak commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms/Problems/StableMarriage/Proposer.cs  1
- Algorithms.Tests/Problems/StableMarriage/GaleShapleyTests.cs  3
- Algorithms/Problems/StableMarriage/GaleShapley.cs  4
- Algorithms/Problems/StableMarriage/Accepter.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6318000&bid=20538743)

2020-10-11 17:35 UTC, brogowski commented
> Overall looks good, I've left a couple of comments on implementation details that are important and make the algorithm run in O(n^3) instead of advertised O(n^2).

Thanks for catching those 👍 - all implemented already.

2020-10-11 17:36 UTC, siriak commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms/Problems/StableMarriage/GaleShapley.cs  4
- Algorithms.Tests/Problems/StableMarriage/GaleShapleyTests.cs  3
- Algorithms/Problems/StableMarriage/Accepter.cs  2
- Algorithms/Problems/StableMarriage/Proposer.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6318000&bid=20538743)

2020-10-12 06:55 UTC, siriak approved these changes
Thanks!

2020-10-12 06:56 UTC, merged