Jump Search implemented
TheAlgorithms/C-Sharp pull request #192
Opened 2020-10-24 07:05 UTC by mondalshubham1

Please include a summary of the change. Please also include relevant motivation and context (if applicable).

- [y] I have performed a self-review of my code
- [y] My code follows the style guidelines of this project
- [y] I have added comments to hard-to-understand areas of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have made corresponding changes to the comments
- [ ] I have made corresponding changes to the README.md

2020-10-24 07:07 UTC, siriak commented on Algorithms/Search/JumpSearcher.cs
> +    /// <typeparam name="T">TODO. 2.</typeparam>
Codacy found an issue: [Complete the task associated to this 'TODO' comment.](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6394504)

2020-10-24 07:07 UTC, siriak commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- Algorithms/Search/JumpSearcher.cs  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6394504&bid=20737350)

2020-10-24 07:07 UTC, siriak commented on Algorithms/Search/JumpSearcher.cs
> +                if (prev == Math.Min(step, n))
Codacy found an issue: [Do not check floating point equality with exact values, use a range instead.](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6394504)

2020-10-24 07:07 UTC, siriak commented on Algorithms/Search/JumpSearcher.cs
> +    /// TODO.
Codacy found an issue: [Complete the task associated to this 'TODO' comment.](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6394504)

2020-10-24 07:28 UTC, siriak commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms/Search/JumpSearcher.cs  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6394504&bid=20737350)

2020-10-24 07:40 UTC, siriak commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms/Search/JumpSearcher.cs  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6394504&bid=20737350)

2020-10-24 07:41 UTC, mondalshubham1 reviewed
Issues mentioned by you taken care of. Please check.

2020-10-24 08:11 UTC, siriak commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms/Search/JumpSearcher.cs  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6394504&bid=20737350)

2020-10-24 08:15 UTC, mondalshubham1 commented
Not able to understand the codcov/patch. What to do next?

2020-10-24 08:19 UTC, mondalshubham1 commented
Add label hacktoberfest-accepted.

2020-10-24 12:34 UTC, siriak requested changes
Read comments and suggestions here:
https://github.com/TheAlgorithms/C-Sharp/pull/146
https://github.com/TheAlgorithms/C-Sharp/pull/185
https://github.com/TheAlgorithms/C-Sharp/pull/192

Also, you need to cover the implementation with tests.
geeksforgeeks.org is a bad source because they often have a lot of bugs and variables are plainly named incorrectly

2020-10-24 12:39 UTC, siriak commented
Only PRs that meet baseline requirements and are likely to be merged without significant changes are marked as hacktoberfest-accepted

2020-10-31 08:26 UTC, siriak commented
Closing because of no activity

2020-10-31 08:26 UTC, closed without merging