Add Luhn algorithm
TheAlgorithms/C-Sharp pull request #195
Opened 2020-11-01 00:48 UTC by NikitaYermak

Add Luhn algorithm. It`s a simple checksum formula used to validate a variety of identification numbers, such as credit card numbers. More information on the link: https://en.wikipedia.org/wiki/Luhn_algorithm.

- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have added comments to hard-to-understand areas of my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have made corresponding changes to the comments
- [x] I have made corresponding changes to the README.md

2020-11-02 19:55 UTC, siriak requested changes
Looks good, I've left some comments though

2020-11-02 19:55 UTC, siriak commented on Algorithms/Other/Luhn.cs
> +            return false;
```suggestion
            return GetSum(number) % 10 == 0;
```

2020-11-02 19:55 UTC, siriak commented on Algorithms/Other/Luhn.cs
> +            int lostIndex = Reverse(number).IndexOf("x", StringComparison.CurrentCultureIgnoreCase);
```suggestion
            int lostIndex = number.Length - 1 - number.LastIndexOf("x", StringComparison.CurrentCultureIgnoreCase);
```

2020-11-02 19:55 UTC, siriak commented on Algorithms/Other/Luhn.cs
> +            string reverseNumber = Reverse(number);
Can you just walk from the end in the loop below?

2020-11-02 19:55 UTC, siriak commented on Algorithms/Other/Luhn.cs
> +                return Validate(number.Replace("x", tempLostNum.ToString())) ? tempLostNum : (lostNum + 9) / 2;
Could you decide on which number to add without validation?

2020-11-02 19:55 UTC, siriak commented on Algorithms/Other/Luhn.cs
> +                    sum += temp;
```suggestion
                    sum += (2 * temp) % 9;
```

2020-11-06 18:50 UTC, siriak approved these changes
Thanks!

2020-11-06 18:50 UTC, merged

2020-11-08 17:19 UTC, NikitaYermak commented
Thanks for improving my code.  I will add some more algorithm soon.