Feature - scapegoat tree
TheAlgorithms/C-Sharp pull request #234
Opened 2021-09-13 17:46 UTC by mime8

This PR introduces new Data Structure - Scapegoat Tree. PR includes Scapegoat Tree class, all related classes and unit tests.

- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Comments in areas I changed are up to date
- [x] I have added comments to hard-to-understand areas of my code
- [x] I have made corresponding changes to the README.md
- [x] I have made corresponding changes to the DIRECTORY.md

2021-09-14 17:01 UTC, siriak requested changes
Hi! Please fix issues Codacy found and make use of Fluent Assertions in tests as we always do. Thanks!

2021-09-14 19:08 UTC, mime8 commented
@siriak , hi! Yes, I know. I tried to fix them yesterday. Will continue tomorrow. I'll let you know when I am done.

2021-11-08 17:32 UTC, siriak commented on DataStructures.Tests/ScapegoatTree/ScapegoatTreeNodeTests.cs
> +
```suggestion
```

2021-11-08 17:32 UTC, siriak commented on DataStructures.Tests/ScapegoatTree/ScapegoatTreeNodeTests.cs
> +
```suggestion
```

2021-11-08 18:00 UTC, siriak approved these changes
LGTM, thanks!

2021-11-08 18:01 UTC, merged