Dijkstra algorithm implementation
TheAlgorithms/C-Sharp pull request #278
Opened 2021-12-08 18:17 UTC by kolosovpetro

- [ ] I have performed a self-review of my code
- [ ] My code follows the style guidelines of this project
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Comments in areas I changed are up to date
- [x] I have added comments to hard-to-understand areas of my code
- [x] I have made corresponding changes to the README.md

2021-12-08 18:17 UTC, kolosovpetro commented
This is a preview PR

2021-12-10 20:01 UTC, siriak requested changes
I have a couple of comments, everything else looks good, thanks!

2021-12-10 20:01 UTC, siriak commented on Algorithms/Graph/Dijkstra/DijkstraAlgorithm.cs
> +                throw new InvalidOperationException($"Vertex does not belong to graph {nameof(startVertex)}.");
Please use ArgumentException(nameof(startVertex))

2021-12-11 17:16 UTC, siriak approved these changes
LGTM, thanks!

2021-12-11 17:17 UTC, merged