Added method for getting every unique permuatation
TheAlgorithms/C-Sharp pull request #293
Opened 2022-02-19 22:21 UTC by ashotjanibekyan

- [ ] I have performed a self-review of my code
- [ ] My code follows the style guidelines of this project
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Comments in areas I changed are up to date
- [ ] I have added comments to hard-to-understand areas of my code
- [ ] I have made corresponding changes to the README.md

2022-02-19 22:47 UTC, ashotjanibekyan commented
Sorry for having a lot of commits, I'm new to pull requests.

Should I create a new branch for every new algorithm in the future?

2022-02-22 08:33 UTC, siriak requested changes

2022-02-22 08:33 UTC, siriak commented on Algorithms.Tests/Strings/PermutationTests.cs
> +
```suggestion
```

2022-02-22 08:33 UTC, siriak commented on Algorithms.Tests/Strings/PermutationTests.cs
> +            var occDic = new Dictionary<char, int>();
Please provide a better name, it's not clear what occ is and Dic is redundant if it means dictionary.

2022-02-22 08:34 UTC, siriak commented
No problem in having many commits, they'll be squashed in one anyway :)

2022-02-22 20:09 UTC, ashotjanibekyan commented
@siriak, thanks for the feedback. I added comments to clarify my intent. Don't remember if the formula had a name (discrete math was years ago), otherwise, I would have added some references too. Is that necessary?

2022-02-24 20:31 UTC, siriak approved these changes
Great explanation, thanks a lot!

2022-02-24 20:31 UTC, merged