Added BoyerMoore.cs
TheAlgorithms/C-Sharp pull request #347
Opened 2022-10-07 03:50 UTC by Wrrikk

- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Comments in areas I changed are up to date
- [x] I have added comments to hard-to-understand areas of my code
- [x] I have made corresponding changes to the README.md

2022-10-08 10:38 UTC, siriak requested changes
Please fix the Codacy check

2022-10-08 10:38 UTC, siriak commented on Algorithms/Search/BoyerMoore.cs
> +        private static bool Verify(IEnumerable<T> input, int size, T candidate)
Please change the function name to be self-descriptive instead of relying on comments

2022-10-08 10:38 UTC, siriak commented on Algorithms/Search/BoyerMoore.cs
> +    /// <typeparam name="T">Type of element stored inside array. 2.</typeparam>
2?

2022-10-08 11:11 UTC, Wrrikk reviewed
Please review the changes

2022-10-09 11:08 UTC, siriak approved these changes
Looks good, thanks!

2022-10-09 11:08 UTC, merged